version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "ecs-demo"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80
